title: Default
sections:
  main:
    title: 'Main'
    fields:
      title:
        title: admin_title
        type: text
        size: col-12
      content:
        title: admin_content
        type: html
        size: col-12
      template:
        title: admin_template
        type: template_select
        size: col-4
      visibility:
        title: admin_visibility
        type: visibility_select
        size: col-4
      date:
        title: admin_date
        type: text
        size: col-4
