# The title of the website
title: "Site title here"

# The description of the website
description: "Site description here"

# The name and email address of the website author
author:
  email: ""
  name: ""

# Set the timezone to be used on the website. For a list of valid timezone
# settings, see: http://php.net/manual/en/timezones.php
timezone: UTC

# Charset
charset: UTF-8

# Date format
date_format: "F d Y H:i:s."

# The theme to use.
#
# Don't edit the provided theme templates directly, because they get updated
# in next releases. If you wish to modify a default theme, copy its folder, and
# change the name here accordingly.
theme: simple

# The locale that'll be used by the Flextype.
locale: "en"

# The default page to use for the homepage.
pages:
  main: home

# Errors
errors:
  display: true

# Cache
cache:
  enabled: true
  prefix: Flextype
  driver: auto
  lifetime: 604800
