title: Flextype
description: 'Modern Open Source Flat-File Content Management System'
keywords: 'flextype, php, cms, flat-file cms, flat cms, flatfile cms, html'
robots: 'index, follow'
author:
  name: ''
  email: ''
timezone: UTC
date_format: 'F d Y H:i:s'
charset: UTF-8
theme: nes
locale: en
pages:
  main: home
errors:
  display: true
cache:
  enabled: true
  prefix: flextype
  driver: auto
  lifetime: 604800
