title: 'Site title here'
description: 'Site description here'
keywords: ''
robots: ''
author:
  name: ''
  email: ''
timezone: UTC
charset: UTF-8
date_format: 'F d Y H:i:s'
theme: default
locale: ru
entries:
  main: home
  media:
    upload_images_quality: 70
    accept_file_types: 'gif, jpg, jpeg, png, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg'
    upload_images_width: 1600
    upload_images_height: 0
  error404:
    title: 'Error 404'
    description: 'We''re sorry but the page you are looking for doesn''t appear to exist!'
    content: 'We''re sorry but the page you are looking for doesn''t appear to exist!'
    template: default
errors:
  display: true
cache:
  enabled: true
  prefix: Flextype
  driver: auto
  lifetime: 604800
