#
# Site configuration
#

title: "Flextype"
description: "Modern Open Source Flat-File Content Management System"
author:
  email: ""

timezone: UTC
date_format: "F d Y H:i:s."
charset: UTF-8

theme: simple

plugins:
  - content-api

locale: "en"

pages:
  main: home

errors:
  display: true

cache:
  enabled: true
  prefix: flextype
  driver: auto
  lifetime: 604800
