title: 'Flextype'
description: 'The Best Open Source Flat-File Content Management System'
keywords: 'flextype, php, cms, flat-file cms, flat cms, flatfile cms, html'
robots: 'index, follow'
author:
  name: ''
  email: ''
