timezone: UTC
date_format: 'F d Y H:i:s'
charset: UTF-8

theme: simple

locale: 'en'

pages:
  main: home

errors:
  display: false

cache:
  enabled: true
  prefix: flextype
  driver: auto
  lifetime: 604800
