title: Default
fields:
  title:
    title: "admin_entries_title"
    type: text
  content:
    title: "admin_entries_content"
    type: html
  template:
    title: "admin_entries_template"
    type: template_select
    size: col-4
  visibility:
    title: "admin_entries_visibility"
    type: visibility_select
    size: col-4
  date:
    title: "admin_entries_date"
    type: text
    size: col-4
